### ISSUE TITLE
Instructions and Docker Support for Running Bamboo Locally

### ISSUE THREAD

**Issue by mblomdahl** [mkdevops-se/bamboo-ci-health#2]
We need to be able to run a local Bamboo server with MySQL, in order to have realistic database contents to generate reports from.

Instructions on how to run MySQL server in Docker: https://hub.docker.com/_/mysql

```yaml
services:
  mysql_server:
    image: mysql/mysql-server:5.7
    container_name: bamboo_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      - MYSQL_DATABASE=bamboo
      - MYSQL_USER=bamboo
      - MYSQL_ROOT_PASSWORD=*******
    volumes:
      - bamboo_mysql:/var/lib/mysql:rw
```

Instructions on how to run Bamboo server in Docker: https://hub.docker.com/r/atlassian/bamboo-server

```yaml
services:
  bamboo_server:
    image: atlassian/bamboo-server:8.2.5
    container_name: bamboo_server
    depends_on:
      - mysql_server
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
    environment:
      - ATL_PROXY_NAME=mblomdahl-mkdevops-se-bamboo-ci-health-7gwq6wr562p5qw-8085.githubpreview.dev
      - ATL_PROXY_PORT=443
      - ATL_LICENSE=AAA...X02kc
      - ATL_JDBC_URL=jdbc:mysql://bamboo_mysql:3306/bamboo
      - ATL_JDBC_USER=bamboo
      - ATL_JDBC_PASSWORD=********
      - ATL_JDBC_TYPE=mysql
    volumes:
      - bamboo_server:/var/atlassian/application/application-data/bamboo:rw
```

Example Ansible tasks for downloading MySQL driver:

```yaml
  # See https://confluence.atlassian.com/bamboo/mysql-289276817.html
- name: download mysql connector
  unarchive:
    src: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.44.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/mysql-connector-java-5.1.44
  tags: bamboo

- name: add mysql connector to bamboo install
  shell: cp -v /tmp/mysql-connector-java-5.1.44/mysql-connector-java-5.1.44-bin.jar
         /opt/atlassian/atlassian-bamboo-latest/lib/
  args:
    creates: /opt/atlassian/atlassian-bamboo-latest/lib/mysql-connector-java-5.1.44-bin.jar
  become: yes
  become_user: bamboo
  tags: bamboo
```

These should be compiled into a `docker-compose.yml` that we can run without too much hazzle.
